### ISSUE TITLE
不支持最新的mpvue-loader吗

### ISSUE THREAD

**Issue by longdan** [F-loat/mpvue-entry#106]
TypeError: Cannot read property 'template' of undefined
    at getCompInfo (D:\worker\sechandwxapp\node_modules\mpvue-loader\lib\mp-compiler\util.js:19:61)
    at createPageMPML (D:\worker\sechandwxapp\node_modules\mpvue-loader\lib\mp-compiler\index.js:41:30)
    at resolve (D:\worker\sechandwxapp\node_modules\mpvue-loader\lib\mp-compiler\index.js:196:9)

**Comment by F-loat** [comment]
请参考 https://github.com/F-loat/mpvue-quickstart/commit/eb4ac7ec8ba7d4dc4742e3f9e382b1762144cd53 修改配置，或重新初始化项目

**Comment by longdan** [comment]
升级到新的mpvue版本后，打包后的app.json文件生成的不对了，新的mpvue好像支持了百度平台 "dev:wx": "node build/dev-server.js wx",
    "start:wx": "npm run dev:wx",
    "build:wx": "node build/build.js wx",
    "dev:swan": "node build/dev-server.js swan",
    "start:swan": "npm run dev:swan",
    "build:swan": "node build/build.js swan",
    "dev": "node build/dev-server.js wx",
    "start": "npm run dev",
    "build": "node build/build.js wx",
    "lint": "eslint --ext .js,.vue src"


我按照新的mpvue修改了打包配置

**Comment by F-loat** [comment]
我晚点再看下，暂时只准备针对微信平台做处理
