### ISSUE TITLE
1.1.3安装配置教程无法编译

### ISSUE THREAD

**Issue by qbob** [F-loat/mpvue-entry#19]

**Comment by F-loat** [comment]
请提供错误信息。。

**Comment by qbob** [comment]
building for production...(node:60280) UnhandledPromiseRejectionWarning: Error: Cannot find module '/www/testwx/miniapp/dist/app.json'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at resetApp (/www/testwx/miniapp/node_modules/mpvue-entry/src/utils.js:39:15)
    at Promise.all.then (/www/testwx/miniapp/node_modules/mpvue-entry/src/utils.js:128:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
(node:60280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:60280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠏ building for production...

**Comment by F-loat** [comment]
晚点会修复

**Comment by qbob** [comment]
目前该扩展是否可用于生产吗？

**Comment by F-loat** [comment]
不好意思，之前更新后没有测试到 build 环节，测试近期会尽量补全，保证可用性，如不放心可之后再使用

**Comment by qbob** [comment]
目前正在使用，期待升级版本

**Comment by F-loat** [comment]
1.1.4 已经发布了，文件暂时改为同步写入
