### ISSUE TITLE
getEntry使用路径参数的问题

### ISSUE THREAD

**Issue by mrichie** [F-loat/mpvue-entry#37]
webpack编译的配置文件中使用方式如下：
const entry = MpvueEntry.getEntry('/src/router/routes.js')

webpack-dev-server --inline --progress --config build/webpack.mpvue.dev.conf.js

编译之后提示模块找不到
Error: Cannot find module '/Users/xx/Workspace/web/node_modules/webpack-dev-server/src/router/routes.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Pages.refresh (/Users/xx/Workspace/web/node_modules/mpvue-entry/lib/parser.js:56:19)

**Comment by F-loat** [comment]
`const entry = MpvueEntry.getEntry('../../src/router/routes.js')`

后面会添加下对绝对路径的支持，目前的识别方式其实是根据执行文件的位置来推断项目根目录的，确实会有问题

**Comment by F-loat** [comment]
新版已支持传入绝对路径
