### ISSUE TITLE
经常在开发时，导致构建工具的开发脚本奔溃

### ISSUE THREAD

**Issue by joenil** [F-loat/mpvue-entry#64]
没有改代码文件，终端里会自动compiling...，然后几次之后就error退出进程了
```
fs.js:1384
    throw error;
    ^

Error: watch /Users/xxx/Development/xxx/src/router/routes.js EMFILE
    at _errnoException (util.js:1041:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at genEntry (/Users/xxx/Development/xxx/node_modules/mpvue-entry/src/index.js:116:6)
    at FSWatcher.fs.watch (/Users/xxx/Development/xxx/node_modules/mpvue-entry/src/index.js:117:55)
    at emitTwo (events.js:125:13)
    at FSWatcher.emit (events.js:213:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1364:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxx@1.0.0 start: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xxx@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2018-09-02T03_02_33_610Z-debug.log
```

**Comment by F-loat** [comment]
routes.js 这个文件的主要内容贴一下

**Comment by joenil** [comment]
一阵子会，一阵子不会。。
``` javascript
module.exports = [
  {
    path: '/pages/home/index',
    name: 'HomeIndex',
    config: {
      enablePullDownRefresh: false,
      backgroundColorTop: '#6686E4',
      backgroundColorBottom: '#f8f8f8'
    }
  },
  {
    path: '/pages/exam/index',
    name: 'ExamIndex',
    config: {
      enablePullDownRefresh: false
    }
  },
  {
    path: '/pages/course/index',
    name: 'CourseIndex',
    config: {
      enablePullDownRefresh: false
    }
  },
  {
    path: '/pages/article/index',
    name: 'ArticleIndex',
    config: {
      enablePullDownRefresh: false,
      navigationBarBackgroundColor: '#fff',
      navigationBarTextStyle: 'black'
    }
  },
  {
    path: '/pages/live/index',
    name: 'LiveIndex',
    config: {
      enablePullDownRefresh: false
    }
  },
  {
    path: '/pages/room/index',
    name: 'RoomIndex',
    config: {
      enablePullDownRefresh: false,
      navigationBarBackgroundColor: '#020b26',
      backgroundColorTop: '#020b26',
      backgroundColorBottom: '#020b26'
    }
  },
  {
    path: '/pages/mine/index',
    name: 'MineIndex',
    config: {
      backgroundColorTop: '#6686E4',
      backgroundColorBottom: '#f8f8f8',
      enablePullDownRefresh: false
    }
  },
  {
    path: '/pages/mine/collected/index',
    name: 'MineCollectedIndex',
    config: {
      enablePullDownRefresh: false
    }
  },
  {
    path: '/pages/mine/history/index',
    name: 'MineHistoryIndex',
    config: {
      enablePullDownRefresh: false
    }
  },
  {
    path: '/pages/mine/subscribed/index',
    name: 'MineSubscribedIndex',
    config: {
      enablePullDownRefresh: false
    }
  },
  {
    path: '/pages/mine/checkin/index',
    name: 'MineCheckinIndex',
    config: {
      enablePullDownRefresh: false
    }
  },
  {
    path: '/pages/webview/index',
    name: 'WebviewIndex',
    config: {
      enablePullDownRefresh: false,
      navigationBarBackgroundColor: '#fff',
      navigationBarTextStyle: 'black'
    }
  },
  {
    path: '/pages/authorization/index',
    name: 'AuthorizationIndex',
    config: {
      enablePullDownRefresh: false,
      navigationBarTitleText: '用户登录'
    }
  }
]

```

**Comment by F-loat** [comment]
你 node 是哪个版本啊，能用其他电脑复现这个问题吗，目前监听基本是直接用的 fs.watch，文件没有修改不应该多次处理的

**Comment by joenil** [comment]
node版本：v8.4.0
mp-entry版本：0.3.7
暂时手上没有其它电脑，无法测试。

**Comment by F-loat** [comment]
0.3.7。。你更新下呗

**Comment by joenil** [comment]
好的，我更新后再观察一下。

**Comment by joenil** [comment]
> @joenil 请问你这个问题解决了吗 我也遇到了 而且我是1.5.2版本

我更新了最新版之后，目前没有再遇到过这个问题了。

**Comment by F-loat** [comment]
还有人反馈的话考虑用其他方式监听文件改动
